version: 2.0.0.{build}
configuration: Release
os: Visual Studio 2017

before_build:
  - nuget restore
  - ps: .\bump-version.ps1

build:
  verbosity: minimal

artifacts:
  - path: BuildVision\bin\Release\BuildVision.vsix

deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: nGrUXPrcAzk/9OZBIUt/T4VpJtLC/4H7CMy2sdwTowPdT/8DPYmZzRaL/IUU5e2u
    artifact: BuildVision\bin\Release\BuildVision.vsix
    prerelease: true
    force_update: true
    on:        
        appveyor_repo_tag: true