version: 1.5.0.{build}
configuration: Release
os: Visual Studio 2017
skip_tags: true

branches:
  only:
    - master
    - dev

before_build:
  - nuget restore
  - ps: .\bump-version.ps1

build:
  verbosity: minimal

artifacts:
  - path: BuildVision\bin\Release\BuildVision.vsix