version: 1.5.0.{build}
configuration: Release
os: Visual Studio 2017
skip_tags: true

branches:
  only:
    - master

before_build:
  - ps: .\bump-version.ps1

build:
  verbosity: minimal

artifacts:
  - path: Source\bin\Release\BuildVision.vsix
